# Generated by Django 4.2.9 on 2024-06-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConvertedTexts',
            new_name='ConvertedText',
        ),
    ]
